# model settings
temperature = 1.0
model = dict(
    type='MoCoV3',
    base_momentum=0.99,  # 0.99 for 100e and 300e, 0.996 for 1000e
    data_preprocessor=dict(
        mean=(255/2, 255/2, 255/2),
        std=(255/2, 255/2, 255/2),
        bgr_to_rgb=True),
    backbone=dict(
        type='VSGenerator',
        input_channels=3,
        output_channels=3,
        ida_channels=64,
        channels=[16, 32, 64, 128, 256, 512],
        head_channels=[64, 32],
        levels=[1, 1, 1, 2, 2, 1],
        norm_name='batch',
        pool_name='avg',
        apply_tanh=False,
        padding_mode='replicate',
        out_indices=[-1],  # 0: conv-1, x: stage-x
        ),
    neck=dict(
        type='NonLinearNeck',
        in_channels=64,
        hid_channels=4096,
        out_channels=256,
        num_layers=2,
        with_bias=False,
        with_last_bn=True,
        with_last_bn_affine=False,
        with_last_bias=False,
        with_avg_pool=True,
        vit_backbone=False),
    head=dict(
        type='MoCoV3Head',
        predictor=dict(
            type='NonLinearNeck',
            in_channels=256,
            hid_channels=4096,
            out_channels=256,
            num_layers=2,
            with_bias=False,
            with_last_bn=False,
            with_last_bn_affine=False,
            with_last_bias=False,
            with_avg_pool=False),
        loss=dict(type='mmcls.CrossEntropyLoss', loss_weight=2 * temperature),
        temperature=temperature))
